version: '3.7'

services:
  mqtt-broker:
    image: eclipse-mosquitto:1.6.15
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto/config:/mosquitto/config
      - ./config/mosquitto/data:/mosquitto/data
      - ./config/mosquitto/log:/mosquitto/log

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: sensor_data_DB
      INFLUXDB_USER: user_tg
      INFLUXDB_USER_PASSWORD: password_tg
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin123
    volumes:
      - ./config/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data

  iot-app:
    build:
      context: ./app
    container_name: iot-app
    privileged: true
    volumes:
      - /dev:/dev
    environment:
      - MQTT_BROKER=mqtt-broker
      - INFLUXDB_HOST=influxdb
    depends_on:
      - mqtt-broker
      - influxdb
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana_data:
  nodered_data:
